window.SITE_DATA = {
  "exportedAt": "2026-06-16T02:36:11Z",
  "submissionsOpen": true,
  "members": [
    "陳至齊",
    "白鈞任",
    "王湘晴",
    "顏加佳",
    "林芸禾",
    "林育伶",
    "王婕語",
    "林甄芃",
    "曹艾可",
    "周晴喜",
    "李蘅容",
    "謝子亮",
    "邱泳淳",
    "洪語婕",
    "黃歆婷",
    "黃浩哲",
    "馬唯基",
    "謝弘楷",
    "林韶毅",
    "王澤",
    "李昀衡",
    "陳杰昇",
    "黃威翔",
    "楊昊寧",
    "黃翊軒",
    "廖晨佑",
    "邱宗豪",
    "歐曜德",
    "許庭睿",
    "林恩宇",
    "許智翔",
    "胡彥博",
    "張允睿",
    "陳立品",
    "蔡允弘",
    "潘彥均",
    "廖丞宥",
    "翁詩宸",
    "楊博安",
    "陳勁諺",
    "林宗穎",
    "蔡亞莫",
    "陳儆熙",
    "李詣超"
  ],
  "songs": [
    {
      "id": "788665df-f77f-4682-8fa1-89b8758702c0",
      "title": "放過我吧",
      "arranger": "全體成員",
      "composer": "謝弘楷、謝子亮",
      "lyricist": "謝弘楷",
      "lyrics": "為什麼他們笑得 如此猖狂\n憑甚麼壞人要 由我來當\n在世人眼中 我是多麼骯髒\n但 那又怎樣\n\n他們不斷翻閱 我的過往\n那種痛苦回憶 不值得收藏\n無名的罪狀 顯得惡名昭彰\n嘲笑瘋狂 卻無視世界荒唐\n\n放過我吧 我不想再去面對\n受夠了啊 內心支離破碎\n接受一切的敗北 鮮花有天也會枯萎\n你討厭嗎 生在這個世界\n\n儘管笑吧 身旁環繞卑微\n那又怎樣 沒人在乎是非\n沒來由的崩潰 早就哭乾了眼淚\n直到最後 我變成哪個誰 如此狼狽\n\n他們笑得 如此猖狂\n憑甚麼壞人要 由我來當\n在世人眼中 我是多麼骯髒\n但 那又怎樣\n\n他們不斷翻閱 我的過往\n那種痛苦回憶 不值得收藏\n無名的罪狀 顯得惡名昭彰\n嘲笑瘋狂 卻無視世界荒唐\n\n放過我吧 我不想再去面對\n受夠了啊 內心支離破碎\n接受一切的敗北 鮮花有天也會枯萎\n你討厭嗎 生在這個世界\n\n儘管笑吧 身旁環繞卑微\n那又怎樣 沒人在乎是非\n沒來由的崩潰 早就哭乾了眼淚\n直到最後 我變成哪個誰 如此狼狽\n\n我想躲開 一切虛偽 \n只想逃離到 無盡的深淵\n在爭議之下 被烙下多少傷疤\n幸好我不會 被黑夜欺騙\n\n放過我吧 我不想再去面對\n受夠了啊 內心支離破碎\n接受一切的敗北 會枯萎\n你討厭嗎（我討厭啊） 生在這個世界\n\n儘管笑吧 身旁環繞卑微\n那又怎樣 沒人在乎是非\n沒來由的崩潰 哭乾眼淚\n直到最後 我變成哪個誰 如此狼狽",
      "performers": {
        "KB1": "廖丞宥",
        "鼓": "白鈞任",
        "Bass": "林恩宇",
        "主唱1": "謝弘楷",
        "主唱2": "謝子亮",
        "木吉他1": "林芸禾",
        "電吉他1": "許庭睿"
      },
      "is_eliminated": false,
      "eliminated_at": null,
      "created_at": "2026-06-14T16:10:05.469+00:00",
      "updated_at": "2026-06-14T16:11:55.565+00:00",
      "all_members": ""
    },
    {
      "id": "4560ebcc-5322-4697-8fcc-54bd66904d35",
      "title": "皮克敏",
      "arranger": "全體成員",
      "composer": "蔡亞莫、林芸禾",
      "lyricist": "蔡亞莫",
      "lyrics": "喔明明 已經到了 十二點半\n為什麼 你還沒說晚安\n難道我口中 所謂的浪漫\n是你認為的 一種 壞習慣 \n\n半夜三點 你終於 \n傳訊息 叫我去找你\n我以為 我們能在一起\n你卻叫 我 一起打蘑菇\n\n噢baby 這次是真的不可以\n半夜三點你還約我去散步\n噢Bad day 今天真的不適合你\n浪費生命去散步\n喔好累 雖然我真的很愛你\n但可不可以下次再去\n也許明天會更適合\n\n今天終於可以打遊戲 怎麼有人傳訊息\n拜託可不可以下一次 我今天真的有事情\n\n噢baby 這次是真的不可以\n半夜三點你還約我去散步\n噢Bad day 今天真的不適合你\n浪費生命去散步\n好累 雖然我真的很愛你\n但可不可以下次再去\n也許明天會更適合",
      "performers": {
        "KB1": "王湘晴",
        "鼓": "林育伶",
        "Bass": "林恩宇",
        "主唱1": "蔡亞莫",
        "電吉他1": "林芸禾",
        "電吉他2": "蔡亞莫"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:10:51.736882+00:00",
      "created_at": "2026-05-10T07:05:51.126+00:00",
      "updated_at": "2026-06-14T16:10:51.736882+00:00",
      "all_members": ""
    },
    {
      "id": "0a10bb56-9192-4a12-a71e-50b3ae0546c3",
      "title": "???",
      "arranger": "全體成員",
      "composer": "全體成員",
      "lyricist": "全體成員",
      "lyrics": "？？？",
      "performers": {
        "KB1": "蔡允弘",
        "鼓": "林宗穎",
        "Bass": "翁詩宸",
        "主唱1": "馬唯基",
        "電吉他1": "許庭睿",
        "電吉他2": "曹艾可"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:10:52.829226+00:00",
      "created_at": "2026-05-08T17:07:36.86+00:00",
      "updated_at": "2026-06-14T16:10:52.829226+00:00",
      "all_members": ""
    },
    {
      "id": "f89e5ba7-de2b-4901-8bf9-e9feb30f9c5b",
      "title": "我喜歡的那個你已經死了所以拜託滾出我的生活",
      "arranger": "全體成員",
      "composer": "周晴喜",
      "lyricist": "周晴喜",
      "lyrics": "| 主 |\n還是勉強可以談天說地\n唯獨不談論是什麼關係\n凌晨哭紅 的眼睛 告訴我\n真的不該認識你\n想要恨透你\n\n| 副 |\n後來我們都很有默契\n誰也沒再提\n反正也就朋友而已\n只是為什麼剛好所有情歌都像你\n\n反覆解讀你寫過的詞曲\n猜那會不會也有一點點我\n是我想太多\n\n| 間奏 |\n\n| 主 |\n再次看到獵戶座在閃耀\n想起你那海風般的玩笑\n那之後你 倒是過 得逍遙\n求你別再來打擾\n真的恨透你\n\n| 副 |\n後來我們都很有默契\n誰也沒再提\n到頭來就朋友而已\n只是為什麼你的爛教養要我處理\n\n反覆解讀你寫過的詞曲\n發現這根本對誰都能夠套用\n還好不是我\n\n| 間奏|\n\n| 副 |\n最後我終於恨透了你\n一切卻在 這時說清\n這比欺騙更加要命\n只是為什麼重新當朋友都沒餘地\n\n這是我最後一首關於你\n把我們那些沒說完的曾經\n就爛在回憶裡",
      "performers": {
        "KB1": "王澤",
        "鼓": "林宗穎",
        "Bass": "黃威翔",
        "主唱1": "周晴喜",
        "木吉他1": "王婕語"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:10:53.537233+00:00",
      "created_at": "2026-05-08T15:46:52.85+00:00",
      "updated_at": "2026-06-14T16:10:53.537233+00:00",
      "all_members": ""
    },
    {
      "id": "9a8c9414-48a8-4bfd-a249-160dfca79283",
      "title": "冰店",
      "arranger": "全體成員",
      "composer": "蔡亞莫、楊博安",
      "lyricist": "蔡亞莫",
      "lyrics": "對於那間冰店不是  那麼期待\n 紅色糖水甜味 也不太喜歡\n風吹在臉上還有 夏天的感覺\n 融化的冰已經沿著臉滑下\n\n說是沉澱其實在拖延時間煙霧之中還是 看清了一點\n想抽根煙發現我未滿18歲解鎖手機還是看到那張臉\n\n\n 對你的想念只在 冰融化之前 \n 當你的眼睛不再  看我一眼 \n攤牌之前都還在同一場遊戲\n好笑的我們藏著同一個秘密～\n\n抹茶的滋味他  已經變淡 \n 一個人的感覺 也早就習慣 \n 就算獨自過了多少沉澱時間\n 也找不回那 次愛的初體驗\n\nsolo\n\n 對你的想念只在 冰融化之前 \n 當你的眼睛不再 看我一眼 \n攤牌之前都還在同一場遊戲\n好笑的我們藏著同一個秘密～",
      "performers": {
        "KB1": "胡彥博",
        "鼓": "邱泳淳",
        "Bass": "黃翊軒",
        "主唱1": "蔡亞莫",
        "電吉他1": "蔡亞莫",
        "電吉他2": "楊博安"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:10:54.38789+00:00",
      "created_at": "2026-05-08T15:44:32.371+00:00",
      "updated_at": "2026-06-14T16:10:54.38789+00:00",
      "all_members": ""
    },
    {
      "id": "71b556b8-5b64-44c1-b0a9-2124b46eec32",
      "title": "零時差盛夏",
      "arranger": "全體成員",
      "composer": "謝子亮、楊博安",
      "lyricist": "楊博安",
      "lyrics": "/主\n獨自一人走在 空盪的街區 \n回想今天的努力\n只剩下時針 空轉的軌跡 \n到底什麼時候能夠抽離\n\n/導\n細微瑣碎的壓力 一點一滴 \n壓抑著自己 慢慢成堆累積\n深夜裡多少惆悵的情緒\n全部瀕臨潰堤\n\n/副\n那就算了吧 越迂迴越掙扎\n就背著吉他 去看一看泳爍的浪花\n夕陽下 屏蔽掉時差\n譜寫屬於 我們的盛夏\n就放縱不去計較代價\n看天邊的晚霞 想著心中的他\n\n/主\n獨自一人走在 空盪的街區 \n回想今天的努力\n只剩下時針 空轉的軌跡 \n到底什麼時候能夠抽離\n\n/導\n細微瑣碎的壓力 一點一滴 \n壓抑著自己 慢慢成堆累積\n深夜裡多少惆悵的情緒\n全部瀕臨潰堤\n\n/副\n那就算了吧 越迂迴越掙扎\n就背著吉他 去看一看泳爍的浪花\n夕陽下 屏蔽掉時差\n譜寫屬於 我們的盛夏\n就放縱不去計較代價\n看天邊的晚霞 想著心中的他\n\n/橋\n盡情 喧嘩 放肆的表達\n無牽 無掛 絢爛的煙花\n喧囂繁華  走不完的天涯\n壓抑崩塌 都融化又蒸發\n眼中無暇 滿眼都是你啊\n\n/副\n那就算了吧 越迂迴越掙扎\n就背著吉他 去看一看泳爍的浪花\n夕陽下 屏蔽掉時差\n譜寫屬於 我們的盛夏\n就放縱不去計較代價\n看天邊的晚霞 想著心中的他",
      "performers": {
        "鼓": "洪語婕",
        "Bass": "黃翊軒",
        "主唱1": "楊博安",
        "主唱2": "謝子亮",
        "木吉他1": "林芸禾",
        "電吉他1": "曹艾可"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:10:55.662994+00:00",
      "created_at": "2026-05-08T15:43:41.865+00:00",
      "updated_at": "2026-06-14T16:10:55.662994+00:00",
      "all_members": ""
    },
    {
      "id": "1f05a2b2-4fe2-40aa-8677-cddcca2b179c",
      "title": "蔡允弘暴斃歌",
      "arranger": "全體成員",
      "composer": "許庭睿",
      "lyricist": "馬唯基",
      "lyrics": "a",
      "performers": {
        "KB1": "蔡允弘",
        "鼓": "林宗穎",
        "Bass": "翁詩宸",
        "主唱1": "馬唯基",
        "電吉他1": "許庭睿"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:10:57.996195+00:00",
      "created_at": "2026-05-08T15:41:26.788+00:00",
      "updated_at": "2026-06-14T16:10:57.996195+00:00",
      "all_members": ""
    },
    {
      "id": "107735b5-1e99-4860-8dc1-6954ddab801b",
      "title": "給自己留一份溫柔",
      "arranger": "全體成員",
      "composer": "謝子亮",
      "lyricist": "謝子亮",
      "lyrics": "望著星空\n誰能成為你的窗口\n眼淚滑落\n誰能夠訴說\n\n有沒有過一個人\n眼神總是為他停留。\n不自覺他早已\n形塑了你青春的種種\n\n有沒有過一瞬間\n愛他比愛自己更多\n放手又多沈重\n怎麼解脫\n\n誰的青春沒遺憾過\n已經留下夠多\n時間說\n它沒有白白地走\n\n有沒有過一個人\n眼神總是為他停留。\n不自覺他早已\n形塑了你青春的種種\n\n有沒有過一瞬間\n愛他比愛自己更多\n放手又多沈重\n怎麼解脫\n\n即使意義有所不同\n還是希望時間能撫平傷痛\n別對自己過於苛求\n放下會比較好過\n\n願故事的盡頭\n你能夠笑著說\n你不曾後悔過\n只是偶爾想起年輕時候\n曾有個人陪你走",
      "performers": {
        "KB1": "顏加佳",
        "鼓": "邱泳淳",
        "Bass": "黃歆婷",
        "主唱1": "謝子亮",
        "木吉他1": "林甄芃",
        "電吉他1": "曹艾可"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:10:59.78024+00:00",
      "created_at": "2026-05-08T15:40:35.542+00:00",
      "updated_at": "2026-06-14T16:10:59.78024+00:00",
      "all_members": ""
    },
    {
      "id": "993d3877-e780-4528-8ee9-18f3641a3e33",
      "title": "Like I Do",
      "arranger": "全體成員",
      "composer": "謝子亮",
      "lyricist": "顏加佳",
      "lyrics": "/主\nCan't believe it has been six months \nWe haven't spoken ever since\nYou and I sure seemed like something\nOr was it just me daydreaming \n\n/導\nKeep telling myself it's over\nMy girl you deserve way better\nSwear I'll get over you this winter\nOh god who am I fooling\n\n/副\nI hope you're not doing fine\nI hope I still haunt your mind\nLike the way you do to mine\nCan't be the only heart broken \n\nI still crave to hear your sound\nBut I should be over you\nCan't forget the way you smile \nBut I should be over you\n\n/主2\nYou easily caught my attention\nDid you even have the intention  \nMaybe it's wrong from the beginning \nI cried even though we were nothing \n\n/導\nKeep on telling myself it's over\nMy girl you deserve way better\nSwear I'll get over you this winter\nOh god who am I fooling\n\n/副\nI hope you're not doing fine\nI hope I still haunt your mind\nLike the way you do to mine\nCan't be the only heart broken \n\nI still crave to hear your sound\nBut I should be over you\nCan't forget the way you smile \nBut I should be over you\n\n/橋\nI hope you \nstay awake like I do\ncry to sleep like I do\nfeel alone like I do \nfall in love like I do I do\n\n/副\nI hope you're as heart broken\nI hope you can't just move on\nIs it awful to think so\nFor heaven's sake I don't know\n\nI still crave to hear your sound\nBut I should be over you \nCan't forget the way you smile \nBut I should be over you",
      "performers": {
        "KB1": "林甄芃",
        "鼓": "邱泳淳",
        "Bass": "黃歆婷",
        "主唱1": "謝子亮",
        "主唱2": "顏加佳",
        "木吉他1": "謝子亮",
        "電吉他1": "曹艾可"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:01.669196+00:00",
      "created_at": "2026-05-08T15:38:27.551+00:00",
      "updated_at": "2026-06-14T16:11:01.669196+00:00",
      "all_members": ""
    },
    {
      "id": "6ef7c8f1-8e4e-4c84-a3df-43779305217e",
      "title": "妳的蹤影",
      "arranger": "全體成員",
      "composer": "全體成員",
      "lyricist": "全體成員",
      "lyrics": "",
      "performers": {
        "KB1": "蔡允弘",
        "鼓": "林宗穎",
        "Bass": "翁詩宸",
        "主唱1": "馬唯基",
        "電吉他1": "許庭睿"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:04.409446+00:00",
      "created_at": "2026-05-08T15:37:21.999+00:00",
      "updated_at": "2026-06-14T16:11:04.409446+00:00",
      "all_members": ""
    },
    {
      "id": "a61abaf2-3d47-4a5c-963d-b389f637546c",
      "title": "下一個春天",
      "arranger": "全體成員",
      "composer": "謝子亮",
      "lyricist": "林甄芃",
      "lyrics": "主歌1\n櫻花盛開的季節\n花瓣飄落在指尖\n我觸碰幸福邊緣\n卻以為擁有全世界\n\n雨水敲打著屋簷\n包圍透明的愛戀\n無數次許下心願\n卻從未抵達你窗邊\n\n導歌\n我以為將那片花瓣握緊\n春天就不會凋零\n我用回憶模糊我的眼睛\n直到分不清四季\n\n副歌\n我曾渴求過一束鮮紅的認同\n深夜裡無數次將自己葬送\n淚水笑容都沈寂在泥土中\n慢慢被時間帶走 \n\n主歌2\n櫻花盛開的季節\n花瓣散落在眼前\n像幸福的分界線\n卻不再和你有關聯\n\n雨水敲打著屋簷\n淋濕了我的雙眼\n曾許下那些心願\n也不再期待被看見\n\n導歌\n我以為將那片花瓣握緊\n春天就不會凋零\n我用回憶模糊我的眼睛\n直到分不清四季\n\n副歌\n我曾渴求過一束鮮紅的認同\n深夜裡無數次將自己葬送\n淚水笑容都沈寂在泥土中\n慢慢被時間帶走 \n\n橋\n或許你從未如我所想\n又或許你始終一樣\n我們之間的時差\n讓我錯過了多少次晚霞\n\n副歌\n我曾渴求過一束鮮紅的認同\n深夜裡無數次將自己葬送\n淚水笑容都沈寂在泥土中\n\n枯萎的夢編織成了新的宇宙\n遺憾終於綻放為燦爛花朵\n我會走向屬於我的自由\n下一個春天來臨後",
      "performers": {
        "KB1": "顏加佳",
        "鼓": "邱泳淳",
        "Bass": "黃歆婷",
        "主唱1": "曹艾可",
        "主唱2": "林甄芃",
        "電吉他1": "謝子亮",
        "電吉他2": "林甄芃"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:05.175901+00:00",
      "created_at": "2026-05-08T15:27:37.966+00:00",
      "updated_at": "2026-06-14T16:11:05.175901+00:00",
      "all_members": ""
    },
    {
      "id": "fe939433-f2dc-46bd-bc7d-2cc6347bac25",
      "title": "斃",
      "arranger": "全體成員",
      "composer": "許庭睿",
      "lyricist": "許庭睿",
      "lyrics": "",
      "performers": {
        "鼓": "白鈞任",
        "Bass": "林恩宇",
        "主唱1": "陳至齊",
        "電吉他1": "許庭睿",
        "電吉他2": "林芸禾"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:05.348704+00:00",
      "created_at": "2026-05-08T15:00:52.607+00:00",
      "updated_at": "2026-06-14T16:11:05.348704+00:00",
      "all_members": ""
    },
    {
      "id": "70ea374b-3fb6-4d77-8558-e28e7cf52dc6",
      "title": "吵吵吵吵吵",
      "arranger": "全體成員",
      "composer": "陳至齊",
      "lyricist": "陳至齊",
      "lyrics": "",
      "performers": {
        "鼓": "林宗穎",
        "Bass": "林恩宇",
        "主唱1": "陳至齊",
        "電吉他1": "許庭睿",
        "電吉他2": "陳勁諺"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:06.498043+00:00",
      "created_at": "2026-05-08T14:30:20.705+00:00",
      "updated_at": "2026-06-14T16:11:06.498043+00:00",
      "all_members": ""
    },
    {
      "id": "b6578c71-12af-4f33-8f2c-1cf1932f869e",
      "title": "中場休息",
      "arranger": "全體成員",
      "composer": "馬唯基",
      "lyricist": "馬唯基",
      "lyrics": "Verse\n燈光閃爍 舞台上\n孤獨身影 佇立中央\n故作鎮定 挺起胸膛\n卻無法緩解慌張\n\n十字路口 繁忙車潮\n像心裡的無形吵鬧\n忙著回應 別人的需要\n直到精神已經受不了\n\nPrechorus\n找不到 正常生活的節奏\n四處奔波無法停止的緊湊\n別人無理的請求都欣然接受\n但連睡覺時間都不夠\n\nChorus\n你需要一段 中場的休息\n別等曲終人散的時候才想起\n那疲憊的身體 沉重的呼吸\n沒甚麼理由繼續壓抑\n\n他們沒資格為你人生做決定\n沒用的通知 就儘管把 它 拋 棄\n塞滿的行事曆只會搞砸心情\n此時此刻給自己一段 中場休息\n\n\nVerse\n燈光閃爍 舞台上\n孤獨身影 佇立中央\n故作鎮定 挺起胸膛\n卻無法緩解慌張\n\n十字路口 繁忙車潮\n像心裡的無形吵鬧\n忙著回應 別人的需要\n直到精神已經受不了\n\nPrechorus 2\n逃不掉 腦中慌亂的思緒\n就像節拍忽快又忽慢的旋律\n內心世界不停下著午後雷雨\n無人能夠聽見的憂鬱\n\nChorus 2\n你需要一段 中場的休息\n別等力不從心的時候才想起\n那長久的無力 都沒人注意 \n根本沒理由繼續壓抑\n\n他們沒資格為你人生做決定\n干擾的聲音 就全都拋 到 千 里\n別再拿一堆破事來折磨自己\n此時此刻給自己一段 中場休息\n\nOutro\n茫茫人海之中\n模糊了是非與對錯\n聚光燈下 找回自我",
      "performers": {
        "KB1": "蔡允弘",
        "鼓": "林宗穎",
        "Bass": "翁詩宸",
        "主唱1": "馬唯基",
        "電吉他1": "許庭睿"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:06.626553+00:00",
      "created_at": "2026-05-08T14:00:15.563+00:00",
      "updated_at": "2026-06-14T16:11:06.626553+00:00",
      "all_members": ""
    },
    {
      "id": "117d3b6b-de81-4173-9f74-6160644b83fb",
      "title": "墜",
      "arranger": "全體成員",
      "composer": "謝子亮、林芸禾",
      "lyricist": "林芸禾、陳至齊",
      "lyrics": "主\n\n你說你不會懂\n我的生活\n所以我 學會了沈默\n多渴望你的回應\n杳無音訊 只剩 孤寂\n沉默不語\n\n導\n\n就像隻 遠離火光的 飛蛾\n我偽裝成 素未謀面 的過客\n\n副\n\n愛 不停遠去\n喔你的背影 試圖尋找痕跡\n我是否真的 放下你了\n啊 就別再回憶起\n那些過去的傷\n逃離你的軌跡\n\n導\n\n就像隻 遠離火光的 飛蛾\n我偽裝成 素未謀面 的過客\n\n副\n\n愛 不停遠去\n喔你的背影 試圖尋找痕跡\n我是否真的 放下你了\n啊 就別再回憶起\n那些過去的傷\n逃離你的軌跡\n\n橋\n\n放過我吧（不再去想那些過往）\n相遇的盛夏（剩下殘破的枝芽）\n我裝傻 明知鮮花總會枯萎啊\n\n副\n\n愛 不停遠去\n喔你的背影 試圖尋找痕跡\n我是否真的 放下你了\n啊 就別再回憶起\n那些過去的傷\n逃離你的軌跡",
      "performers": {
        "KB1": "林韶毅",
        "鼓": "林宗穎",
        "Bass": "林恩宇",
        "主唱1": "謝子亮",
        "主唱2": "陳至齊",
        "木吉他1": "林芸禾",
        "電吉他1": "許庭睿"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:07.693836+00:00",
      "created_at": "2026-05-08T13:55:43.773+00:00",
      "updated_at": "2026-06-14T16:11:07.693836+00:00",
      "all_members": ""
    },
    {
      "id": "08feb9f4-b38f-407b-8004-78e865b05114",
      "title": "溫室",
      "arranger": "全體成員",
      "composer": "許庭睿",
      "lyricist": "許庭睿",
      "lyrics": "| 主 |\n潮濕的空氣裹著昨晚沒晾乾的襯衫\n街燈還在漫無目的地泛著黃\n你的影子被拉得很長很長\n長過我們之間沒說出口的那些對話\n\n菸草的味道消失在剛下過雨的巷口\n影子跟著晚風微微顫抖\n\n| 副 |\n我們在灰色的城市裡漫步\n找不到出口卻也不想結束\n讓時間停在模糊的瞬間\n像溫室裡的雜草靜靜蔓延\n\n| 間奏 |\n\n| 主 |\n灰色的天空照亮你睡眼惺忪的目光\n人群之中漫無目的地望著前方\n你的身影被拉得很長很長\n長過我藏在心底沒出口的那些想像\n\n閃爍的餘光消失在嘈雜喧鬧的窗口\n呼吸跟著晚風微微顫抖\n\n| 副 |\n我們在錯位的城市裡漫步\n抓不住彼此卻也不想結束\n讓時間回到模糊的瞬間\n像溫室裡的雜草不肯枯萎\n\n| 間奏 |\n\n| 副 |\n我們在錯位的城市裡漫步\n抓不住彼此卻也不想結束\n讓時間回到模糊的瞬間\n像溫室裡的雜草不肯枯萎",
      "performers": {
        "KB1": "顏加佳",
        "鼓": "胡彥博",
        "Bass": "林恩宇",
        "主唱1": "許庭睿",
        "主唱2": "周晴喜",
        "電吉他1": "王婕語",
        "電吉他2": "許庭睿"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:07.890182+00:00",
      "created_at": "2026-05-08T13:51:56.697+00:00",
      "updated_at": "2026-06-14T16:11:07.890182+00:00",
      "all_members": ""
    },
    {
      "id": "1c4bbc8a-6b71-459c-be84-6e410b270c6a",
      "title": "Goodbye after tonight",
      "arranger": "全體成員",
      "composer": "周晴喜",
      "lyricist": "顏加佳",
      "lyrics": "主\nYour beauty is out of this world\nYou're so fine, I've seen even more\nThe way you dance, the way you move\nI'm head over heels for you\n\n導\nLike that ice cream \ndripping off your tongue \nLike that red wine\nI can't have enough \nI can't resist you my lover in the moonlight \n\n副\nThe thought that's almost upsetting \nWe'll be strangers next morning \nWe both know, need no pretending \nIt's goodbye after tonight\n\n| 間奏 |\n\n主\nIf you want it take a bite\nBe my lover in the moonlight\nHave you ever been to heaven \nIf not I'll take you for a ride\n\n導\nLike that ice cream \ndripping off your tongue \nLike that red wine\nI can't have enough \nI can't resist you my lover in the moonlight \n\n副\nThe thought that's almost upsetting \nWe'll be strangers next morning \nWe both know, need no pretending \nIt's goodbye after tonight\n\n| 間奏 |\n\n副\nThe thought that's almost upsetting \nWe'll be strangers next morning \nWe both know, need no pretending \nIt's goodbye after tonight",
      "performers": {
        "KB1": "許庭睿",
        "鼓": "胡彥博",
        "Bass": "黃翊軒",
        "主唱1": "周晴喜",
        "電吉他1": "王婕語"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:08.477827+00:00",
      "created_at": "2026-05-08T13:46:01.719+00:00",
      "updated_at": "2026-06-14T16:11:08.477827+00:00",
      "all_members": ""
    },
    {
      "id": "0a90d5bc-30a6-46b6-bb4c-c76eb80520d6",
      "title": "終章",
      "arranger": "全體成員",
      "composer": "陳至齊、謝子亮",
      "lyricist": "陳至齊、謝子亮",
      "lyrics": "主1\n\n我們一起吹起的風\n也撐過了洶湧 \n無數風暴之後\n安穩了結果\n\n夜裡不斷地思湧\n也期待能寫出什麼\n感動人的流動\n在幾小時之中\n\n導\n\n現在時光已過 人事已流\n數不盡的碎波\n卻又全都刻在 我們心中\n\n副\n\n我們一起追逐過浪花\n一起走過了盛夏\n在旋律中刻下模樣\n讓音樂記得時光\n\n今天從這裡離開以後\n究竟帶上了什麼 \n又選擇讓什麼留下\n其實已經留下\n一個青春的回答\n\n主2\n\n經歷過的所有夢\n也輪到我們來接手\n也想帶給他們\n一樣的感動\n\n導\n\n現在時光已過 人事已流\n數不盡的碎波\n卻又全都刻在 我們心中 \n\n副\n\n我們一起追逐過浪花\n一起走過了盛夏\n在旋律中刻下模樣\n讓音樂記得時光\n\n今天從這裡離開以後\n究竟帶上了什麼 \n又選擇讓什麼留下\n其實已經留下\n一個青春的回答\n\n橋\n\n奔往塞滿夢的樂園\n就像那年一樣（一個屬於我的世界）\n在舞台上忘記時間（在飛遠之前）\n用音樂築起夢想（許下同個心願）\n音符將我們緊緊串連（站在同一邊）\n成就最耀眼的一天\n\n副\n\n我們一起追逐過浪花\n一起走過了盛夏\n在旋律中刻下模樣\n讓音樂記得時光\n\n今天從這裡離開以後\n究竟帶上了什麼 \n又選擇讓什麼留下\n其實已經留下\n一個青春的回答",
      "performers": {
        "KB1": "蔡允弘",
        "鼓": "周晴喜",
        "Bass": "黃翊軒",
        "主唱1": "謝子亮",
        "主唱2": "陳至齊",
        "木吉他1": "林芸禾",
        "電吉他1": "王婕語"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:08.957034+00:00",
      "created_at": "2026-05-08T13:45:00.209+00:00",
      "updated_at": "2026-06-14T16:11:08.957034+00:00",
      "all_members": ""
    },
    {
      "id": "492250d6-ce0a-43d2-9522-be0719d8398a",
      "title": "laxiy saku lngisiy",
      "arranger": "全體成員",
      "composer": "周晴喜",
      "lyricist": "周晴喜",
      "lyrics": "laqi mu Tayal 我是泰雅族的孩子\nini tnaq kian tala 我們居住的空間已經不夠了\nsigluw llyung musa 我們要沿著河流\nmkaraw rgyax qasa 翻山越嶺\nmaki blaq kian ta 找到適合居住的\nsiqyanu kya nanak lki 勇敢的建立一個部落\n\n| 間奏 |\n\n| 主 |\nmaki squliq ga wal lama mramat 有人只是短暫的出現\nbaha ungat  smyahoq uziy 怎麼可能沒有錯過\n\n| 副 |\nsi p’ubuy qu kay 一句接著一句\ninsuna ka wiwal nyux mlaka 彷彿漂浮的生命\nlaxiy saku lngisiy 不要懷念我\n\n| 間奏 |\n\n| 主 |\nlaxiy klaniy zyuwaw raral hiya ga 不要再提起舊事\nbaha maku bahun mungi lasa hiya 我哪裡會忘記\n\n| 副 |\nsi p’ubuy qu kay 一句接著一句\ninsuna ka wiwal nyux mlaka 彷彿漂浮的生命\nlaxiy saku lngisiy 不要懷念我\n\n| 間奏 |\n\n| 橋 |\nnyux saku mqyanux na maki squ behuy 我會活在風中\ninsuna  ungat  pcingan mu 我的生命沒有結束的一天\n\n| 副 |\nsi p’ubuy qu kay  一句接著一句\ninsuna ka wiwal nyux mlaka 彷彿漂浮的生命\nlaxiy saku lngisiy 不要懷念我",
      "performers": {
        "主唱1": "周晴喜",
        "木箱鼓": "林宗穎",
        "木吉他1": "林芸禾",
        "木吉他2": "謝子亮"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:10.348245+00:00",
      "created_at": "2026-05-08T13:41:31.494+00:00",
      "updated_at": "2026-06-14T16:11:10.348245+00:00",
      "all_members": ""
    },
    {
      "id": "8a111991-4324-4a63-8adb-759276079e3a",
      "title": "6/8 time signature",
      "arranger": "全體成員",
      "composer": "謝子亮",
      "lyricist": "謝子亮",
      "lyrics": "/主\nThey all keep going \nSo you keep chasing \nDay and night \nNight and day\nForget your own timeline \n\n/導\nThe world runs in 4/4 \nBut you live by 6/8\nAn out of sync beat\nCouldn’t keep time couldn’t fit in \nJust live on your timeline \n\n/副\nHalf a step late \njust slightly behind the pace \nIt’s not a defect you need to erase\nNo need to imitate \nJust live on your timeline’s way\n\n/主2\nFollow their clocks\nFollow their way\nAfraid of falling off the beat\nConfusion binds you like chains\n\n/導\nThe world runs in 4/4\nBut you live by 6/8\nAn out of sync beat\nCouldn’t keep time couldn’t fit in \nJust live on your timeline \n\n/副\nHalf a step late \njust slightly behind the pace \nIt’s not a defect you need to erase\nNo need to imitate \nJust live on your timeline’s way\n\n/橋\nDon’t be anxious about \nsomeone else shine \nMove only to the rhythm\nof your own time\n\n/副\nHalf a step late \njust slightly behind the pace \nIt’s not a defect you need to erase\nNo need to imitate \nJust live on your timeline’s way",
      "performers": {
        "KB1": "王湘晴",
        "鼓": "周晴喜",
        "Bass": "林恩宇",
        "主唱1": "謝子亮",
        "木吉他1": "林芸禾",
        "電吉他1": "陳立品"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:10.762583+00:00",
      "created_at": "2026-05-08T13:41:31.393+00:00",
      "updated_at": "2026-06-14T16:11:10.762583+00:00",
      "all_members": ""
    },
    {
      "id": "880ff329-480f-4eb6-b046-52621cea0285",
      "title": "筆先",
      "arranger": "全體成員",
      "composer": "許庭睿",
      "lyricist": "蔡允弘",
      "lyrics": "主\n\n白紙の絵を背に　濃いインクを落とした\n誰もがみうしあう画面の裏\n不確かなデッサン　影に混ざる\n鼓動が跳ねる　バクバク\n\nありふれたデッサンを繰り返す毎日に　さようなら\nインクを今ブチあげたんだ\n動き出す　この夜\n加速する　世界で\n未完成なキャンバスを燃やせ\n\n|KB solo|\n\n導\n\nみろ　群青　夜空　染まる\n誰も追いつけないほどの速度で\n鮮やかな音混ぜて\n新しい明日を描け　染まれ\n\n副\n\n夜をかけ　群青の画譜を切り裂いて\n君と世界塗り替えて　\n滲むインクが遥か彼方の方へ\nこの続き描き切るために\n\n｜間奏｜\n\n\n主\n\n白紙の絵を背に　濃いインクを落とした\n誰もがみうしあう画面の裏\n不確かなデッサン　影に混ざる\n鼓動が跳ねる　バクバク\n\nありふれたデッサンを繰り返す毎日に　さようなら\nインクを今ブチあげたんだ\n動き出す　この夜\n加速する　世界で\n未完成なキャンバスを燃やせ\n\n導\n\n見ろ　群青　夜空　染まる\n誰も追いつけないほどの速度で\n鮮やかな音混ぜて\n新しい明日を描け　染まれ\n\n副\n\n夜をかけ　群青の画譜を切り裂いて\n君と世界塗り替えて　\n滲むインクが遥か彼方の方へ\nこの続き描き切るために",
      "performers": {
        "KB1": "蔡允弘",
        "鼓": "胡彥博",
        "Bass": "黃威翔",
        "主唱1": "周晴喜",
        "電吉他1": "許庭睿",
        "電吉他2": "王婕語"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:11.472367+00:00",
      "created_at": "2026-05-08T13:41:04.338+00:00",
      "updated_at": "2026-06-14T16:11:11.472367+00:00",
      "all_members": ""
    },
    {
      "id": "56ef9c36-11e8-4b00-a392-b5330a10605c",
      "title": "光碟",
      "arranger": "全體成員",
      "composer": "陳至齊",
      "lyricist": "陳至齊、白鈞任",
      "lyrics": "前奏\n\n主：\n繼 到來的意外\n也 混亂了節拍\n想著不會再來的晚安\n我用盡了手段\n卻沒了結期待\n\n誰 會想要離開\n可以（下）共闖的未來\n抱歉你常常跑來大安\n我卻理所當然\n你不會再回來\n\n副：\n懷抱自己的一切\n看著過去在明滅\n曾經說過的話 走過的路\n回頭的畫面\n\n不會再有的體驗\n已經畫上了句點\n在你離開之前 你可否回味\n那一點點 一點點 唯美\n\n間奏（4小節）\n\n主：\n繼到來的意外\n也 混亂了節拍\n最後與你共度的晚餐\n話卻說不出來\n全都是我活該\n\n誰會想要離開\n無處不在的未來\n抱歉你常常跑來大安\n我卻理所當然\n你不會再回來\n\n副：\n那天後我便憔悴\n但你卻依然耀眼\n曾經說過的話 走過的路\n回頭的畫面\n\n最後一次的見面\n落日飛車的光碟\n在你離開之前 請至少回味\n那一點點一點點 唯美\n\n間奏（8小節）\n\n副：\n包裹淚滴的以前\n流下了數個月的戀\n你曾說過的話 一起走過的路\n也都刻在我心間\n\n最後一次的見面\n落日飛車的光碟\n我們分開之前 你能否回味\n那一點點 一點點 從前",
      "performers": {
        "KB1": "蔡允弘",
        "鼓": "白鈞任",
        "Bass": "黃浩哲",
        "主唱1": "陳至齊",
        "電吉他1": "王婕語",
        "電吉他2": "曹艾可"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:12.141629+00:00",
      "created_at": "2026-05-08T13:32:52.987+00:00",
      "updated_at": "2026-06-14T16:11:12.141629+00:00",
      "all_members": ""
    },
    {
      "id": "8760b3a2-202e-475e-8745-81c14f5acde8",
      "title": "嘿啊嗯！",
      "arranger": "全體成員",
      "composer": "陳立品",
      "lyricist": "全體成員",
      "lyrics": "｜前奏8｜\n嘿！\n｜前奏16｜\n\n｜主｜\n床頭的爆米花\n其實沒那麼胖\n為什麼打麻將\n別再說白目話\n菲律賓馬尼拉\n為什麼剪頭髮\n別造謠我壞話\n我要爆炸\n\n啊！\n\n｜導｜\n別吵\n我想你已經全都知道\n台北的星星很少\n我想 逃跑\n信義路學校\n\n嗯！\n\n｜副｜\n每天起床好早\n看到同學好躁\n捷運快要塞爆\n我想逃跑\n\n每天起床好早\n看到同學好躁\n考試快要塞爆\n帶我逃離信義路學校\n\n｜間奏｜\n\n｜導｜\n別吵\n我想你已經全都知道\n台北的星星很少\n我想 逃跑\n信義路學校\n\n嗯！\n\n｜副｜\n每天起床好早\n看到同學好躁\n捷運快要塞爆\n我想逃跑\n\n每天起床好早\n看到同學好躁\n考試快要塞爆\n帶我逃離信義路學校\n\n｜橋｜\n喔喔 快帶我逃跑\n喔喔 信義路學校\n喔喔 讓我繼續去睡覺\n\n｜副｜\n每天起床好早\n看到同學好躁\n捷運快要塞爆\n我想逃跑\n\n每天起床好早\n看到同學好躁\n考試快要塞爆\n帶我逃離信義路學校\n每一天都在遲到\n我們一起翹課好不好\n拜託別把我當掉",
      "performers": {
        "鼓": "白鈞任",
        "Bass": "黃威翔",
        "主唱1": "陳勁諺",
        "木吉他1": "許智翔",
        "電吉他1": "陳立品"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:12.765877+00:00",
      "created_at": "2026-05-08T13:30:59.554+00:00",
      "updated_at": "2026-06-14T16:11:12.765877+00:00",
      "all_members": ""
    },
    {
      "id": "1dafa321-d6af-4409-a120-7b598d20dfd1",
      "title": "捕夢網",
      "arranger": "全體成員",
      "composer": "謝子亮",
      "lyricist": "謝子亮",
      "lyrics": "/主\n你的一舉一動\n都像是精心設計過 \n不曾牽起手 \n卻被牽著走\n\n/副\n是誰先動了心\n又是誰輕易放棄\n不斷拉扯的關係\n卻始終停留在原地\n\n/主2\n就像提線木偶\n思緒不自覺被緊扣 \n心跳在顫動\n是悸動還是擔憂\n\n/副2\n是誰先動了心\n又是誰輕易放棄\n不斷拉扯的關係\n卻始終停留在原地\n\n/橋\n看不見 摸不清 界線在哪裡\n是不是你不斷擅自擬定\n如今期待都落了空\n能不能別讓我記得你來過\n\n/副\n是誰先動了心\n又是誰輕易放棄\n不斷拉扯的關係\n卻始終停留在原地\n\n火花是如此熟悉\n讓這一刻顯得冷清\n殘留著僅存的希冀\n真相卻如此透明",
      "performers": {
        "鼓": "胡彥博",
        "Bass": "林恩宇",
        "主唱1": "謝子亮",
        "木吉他1": "林芸禾",
        "電吉他1": "王婕語"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:13.351096+00:00",
      "created_at": "2026-05-08T13:29:06.1+00:00",
      "updated_at": "2026-06-14T16:11:13.351096+00:00",
      "all_members": ""
    },
    {
      "id": "8f549808-11e7-4816-a849-c763740f175a",
      "title": "反正沒有歌詞就先報歌",
      "arranger": "白鈞任、陳立品、黃威翔、許庭睿",
      "composer": "白鈞任、許庭睿、黃威翔、陳立品",
      "lyricist": "",
      "lyrics": "",
      "performers": {
        "鼓": "白鈞任",
        "Bass": "黃威翔",
        "電吉他1": "陳立品",
        "電吉他2": "許庭睿"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:13.583246+00:00",
      "created_at": "2026-05-08T13:28:57.361+00:00",
      "updated_at": "2026-06-14T16:11:13.583246+00:00",
      "all_members": ""
    },
    {
      "id": "1d6773c3-fffa-44f7-b121-c595d15571b0",
      "title": "孤不芳自不賞",
      "arranger": "全體成員",
      "composer": "周晴喜",
      "lyricist": "陳勁諺",
      "lyrics": "| 主 |\n獨自一人坐上 那回家的末班車\n望著車窗倒影 憔悴得像死人\n靜音關機丟掉 逃離刺耳的喧鬧\n安靜讓我逍遙 才怪 是讓我內耗\n\n| 副 |\n我想 像你一樣站在巨人的肩膀上\n其實 懼高症是上天給我的懲罰\n我想 像你一樣成為大家的目光 \n可是 現實卻把我推向鏡頭遠方\n\n| 間奏 |\n\n| 主 |\n強者總是孤獨 那我肯定不會輸\n以為已經進步 卻還是一如當初\n重感情的廢物 至少 感情充足\n但我唱只算是 沒感情的廢物\n\n| 副 |\n我想 像你一樣站在巨人的肩膀上\n其實 懼高症是上天給我的懲罰\n我想 像你一樣成為大家的目光 \n可是 現實卻把我推向鏡頭遠方\n\n| 間奏 |\n\n| 橋 |\n無數黑夜低頭\n眼淚不自覺下落\n自信是稀有品種\n我這種人不配擁有\n\n| 副 |\n我想 像你一樣站在巨人的肩膀上\n其實 懼高症是上天給我的懲罰\n我想 像你一樣成為大家的目光 \n可是 現實卻把我推向鏡頭遠方",
      "performers": {
        "KB1": "林韶毅",
        "鼓": "周晴喜",
        "Bass": "黃翊軒",
        "主唱1": "陳勁諺",
        "木吉他1": "許智翔",
        "電吉他1": "王婕語"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:13.964564+00:00",
      "created_at": "2026-05-08T13:17:18.028+00:00",
      "updated_at": "2026-06-14T16:11:13.964564+00:00",
      "all_members": ""
    },
    {
      "id": "b6f3f923-4ff0-49c7-87aa-d6b569b97868",
      "title": "夢",
      "arranger": "全體成員",
      "composer": "林芸禾",
      "lyricist": "林芸禾、謝弘楷",
      "lyrics": "| 主 |\n空無一人的寂靜\n我停在這裡\n一望無際的白裡\n只剩 自己   \n\n我看見了你\n朦朧的光影\n\n| 導 |\n腳步落下沒有回音\n沒明說的默契\n望著逐漸模糊的你\n無法觸及\n\n| 主 |\n空無一人的寂靜\n我停在這裡\n一望無際的白裡\n找到 了你\n\n蔓延的黎明\n閃動的光影\n\n| 導 |\n腳步落下起了漣漪\n沒明說的默契\n轉圈在無重的境\n笑得很輕\n\n| 副 |\n我只想和你在夢裡玩耍\n活在兒時夢想中的童話\n在邊界裡反覆流浪\n就漂流著 漂流在這無垠蒼茫\n\n| 副 |\n我只想和你留在夢裡玩耍\n讓風帶著我們慢慢去闖蕩\n期盼著哪天能找到解答\n無憂無慮 漂流在這無垠蒼茫",
      "performers": {
        "KB1": "謝子亮",
        "鼓": "胡彥博",
        "Bass": "黃威翔",
        "主唱1": "周晴喜",
        "主唱2": "林芸禾",
        "木吉他1": "林芸禾",
        "電吉他1": "陳立品"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:14.619329+00:00",
      "created_at": "2026-05-08T13:12:43.604+00:00",
      "updated_at": "2026-06-14T16:11:14.619329+00:00",
      "all_members": ""
    },
    {
      "id": "7416a918-deaa-4186-b7c3-8e1a5df9b61f",
      "title": "路邊",
      "arranger": "全體成員",
      "composer": "謝弘楷",
      "lyricist": "謝弘楷",
      "lyrics": "《副歌》\n看你把阮的情 阮的心 擲塗跤\n我看著你 你兩人 佇亭仔跤\n想講的話 到喙邊 攏轉聲\n原來 我是笑詼一攤\n\n《主歌》\n看無人的火車 永遠行到遐\n看無人的心酸 竟會發現我\n阮的時間 停停斷斷 到底是啥\n著是 不甘\n\n《導歌》\n是你 將阮的愛情變做一場戲\n是我 把阮的真心變做分開\n是你 用言語𧿬踏阮的過去\n我哪會知影 是我太過認真\n\n《副歌》\n看你把阮的情 阮的心 擲塗跤\n我看著你 你兩人 佇亭仔跤\n想講的話 到喙邊 攏轉聲\n原來 我是笑詼一攤\n\n伊牽起你的手 欲離開 我身邊\n我徛佇遮 暗巷內 揣著你\n我付出全心全意\n最後騙我的人 是你\n\n《導歌》\n是你 將阮的愛情變做一場戲\n是我 把阮的真心變做分開\n是你 用言語𧿬踏阮的過去\n我哪會知影 是我太過認真\n\n《副歌》\n看你把阮的情 阮的心 擲塗跤\n我看著你 你兩人 佇亭仔跤\n想講的話 到喙邊 攏轉聲\n原來 我是笑詼一攤\n\n伊牽起你的手 欲離開 我身邊\n我徛佇遮 暗巷內 揣著你\n我付出全心全意\n最後騙我的人 是你",
      "performers": {
        "KB1": "謝子亮",
        "鼓": "胡彥博",
        "Bass": "黃威翔",
        "主唱1": "謝弘楷",
        "木吉他1": "林芸禾",
        "電吉他1": "陳立品"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:15.717366+00:00",
      "created_at": "2026-05-08T13:07:31.36+00:00",
      "updated_at": "2026-06-14T16:11:15.717366+00:00",
      "all_members": ""
    },
    {
      "id": "345728be-29fa-4149-8979-3dfd76db6fbb",
      "title": "天亮之間",
      "arranger": "全體成員",
      "composer": "謝子亮",
      "lyricist": "謝弘楷",
      "lyrics": "《主歌》\n窗外的風沒有方向\n卻反覆拂過同一扇窗\n我學著把聲音收好\n折進口袋 假裝沒有重量\n多猖狂的我 又到哪個年代\n\n《副歌》\n我試著走在天亮之前\n讓名字被風帶走一些\n街燈一盞盞沖淡\n回聲反覆描寫著殘缺\n\n我以為會好點 在那瞬間\n奮力伸住的手卻被退回\n遠方的彼岸 無盡的黑\n我正在活在從前\n\n《主歌》\n或許只是一次並肩\n影子不再屬於地面\n從前破碎的聲音\n逐漸慢慢被拼回\n多零碎的我 又到哪個年代\n\n《副歌》\n我仍然走在天亮之前\n讓名字慢慢學會出現\n街燈一盞盞流竄\n回聲接回遺落的時間\n\n我以為會好點 在那瞬間\n奮力伸出的手 接住一些\n遠方的彼岸 無盡的黑\n我正在離開從前\n\n《橋》\n讓風穿過痕跡的地方\n不急著為傷口原諒\n不需要證明 不需流淚\n慢慢學會去面對\n\n《副歌》\n我終於走在天亮之間\n讓名字安穩停在路邊\n街燈一盞盞流轉\n回聲找回遺落的時間\n\n我以為會好點 在那瞬間\n奮力伸住的手 早已依偎\n遠方的彼岸 無盡的黑\n我不再活在從前",
      "performers": {
        "KB1": "林甄芃",
        "鼓": "王湘晴",
        "Bass": "黃歆婷",
        "主唱1": "李蘅容",
        "木吉他1": "謝弘楷",
        "電吉他1": "謝子亮"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:11:17.858733+00:00",
      "created_at": "2026-05-08T13:06:23.342+00:00",
      "updated_at": "2026-06-14T16:11:17.858733+00:00",
      "all_members": ""
    },
    {
      "id": "666a98f4-e7b4-459a-9df8-1e3ed070012c",
      "title": "迂迴",
      "arranger": "全體成員",
      "composer": "周晴喜、楊博安",
      "lyricist": "周晴喜、楊博安",
      "lyrics": "| 主 |\n街燈一盞一盞熄滅\n喧囂的城市 也在慢慢沉睡\n螢幕亮了又暗反覆上演\n把心中的話一遍遍收回\n\n只剩啜泣聲在作祟\n偏偏那些畫面清晰得很可悲\n你對他的笑我重複體會\n一寸寸割往我心裡面\n\n| 主 |\n只剩朋友這個定位\n偏偏那些靠近總讓人很誤會\n你對我的笑我只能回味\n我心中明暸 不能越界\n\n| 副 |\n深夜裡 的眼淚 浸濕整個房間\n曾相愛 的畫面 沈痛卻想念\n刀划過 我的心扉 過多失血 無法調節 都瓦解\n剩執念 在迂迴 又輾轉了幾遍\n內心早 已擱淺 無法抽離的思念\n已讀後 的敷衍 顯得格外刺眼\n回憶在 腦海 重播直到 天亮前\n\n\n| 副 |\n深夜裡 的眼淚 浸濕整個房間\n曾相愛 的畫面 沈痛卻想念\n刀划過 我的心扉 過多失血 無法調節 都瓦解\n剩執念 在迂迴 又輾轉了幾遍\n內心早 已擱淺 無法抽離的思念\n已讀後 的敷衍 顯得格外刺眼\n回憶在 腦海 重播直到 天亮前",
      "performers": {
        "主唱1": "周晴喜",
        "主唱2": "楊博安",
        "木箱鼓": "白鈞任",
        "木吉他1": "王婕語",
        "木吉他2": "林芸禾"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:10:47.875501+00:00",
      "created_at": "2026-05-08T13:04:35.092+00:00",
      "updated_at": "2026-06-14T16:10:47.875501+00:00",
      "all_members": ""
    },
    {
      "id": "a033ed77-8482-4425-b9a1-069315679bfd",
      "title": "我以為就是你",
      "arranger": "全體成員",
      "composer": "黃威翔",
      "lyricist": "黃威翔",
      "lyrics": "主\n表演的劇情\n妳找我要哀居\n興奮的表情\n我以為就是妳\n一切都很順利\n妳說妳很開心\n幸福的語氣\n我覺得就是妳\n\n副\n好想回到那樣的過去\n我們曾經靠的那麼近\n需要 我需要 我需要 我需要妳\n我 好想你\n陌生的壓力\n默默地折磨著妳\n想要 我想要 我想要 我想要妳\n我 好想妳\n\n主\n從前的甜蜜\n默默消逝而去\n未讀的訊息\n我一直在等妳\n莫名的頻率\n妳說妳不開心\n冷漠的語氣\n我還是在等妳\n\n副\n好想回到那樣的過去\n也知道一切都回不去\n我需要妳\n\n副\n好想回到那樣的過去\n也知道一切都回不去\n需要 我需要 我需要 我需要妳\n我 好想妳\n陌生的壓力\n默默地折磨著妳\n想要 我想要 我想要 我想要妳\n我 好想妳\n只怕一切都來不及\n以後就別再輕易放棄\n想要 我想要 我想要 我想要妳\n我 好想妳",
      "performers": {
        "KB1": "周晴喜",
        "鼓": "胡彥博",
        "Bass": "黃威翔",
        "主唱1": "黃威翔",
        "電吉他1": "陳立品",
        "電吉他2": "王婕語"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:10:46.561115+00:00",
      "created_at": "2026-05-08T12:58:02.725+00:00",
      "updated_at": "2026-06-14T16:10:46.561115+00:00",
      "all_members": ""
    },
    {
      "id": "9ad32ee8-3503-49ec-9c1d-23f232857758",
      "title": "誤會",
      "arranger": "全體成員",
      "composer": "陳立品",
      "lyricist": "陳立品",
      "lyrics": "（主）\n想佔有你素顏 洗完澡後 頭髮還是濕的最美 \n每當你閉上眼 當你想睡 你想起有我要安慰\n（導）\n會錯意的手在什麼時候 把你拉走\n（副）\n我們的感覺是誤會太擔心對不對 \n你微笑許的願望太直接太濃烈 \n我實現不了你想要的每一天每一夜 \n也感覺到了我們之間每一天在改變 \n能不能再給我再一兩天的時間 \n我改變說完了就希望你能諒解 \n我想跟你去你說過的每一間咖啡店 \n讓最初的感覺在這時候繞一個圈\n（主）\n（空白頁）\n好奇你過得怎樣 跟我還在的時候很像\n他們都說我做事穩當 但對不起我這次是個混帳 \n（導）\n會錯意的手在什麼時候 把你拉走\n（副）\n我們的感覺是誤會太擔心對不對 \n你微笑許的願望太直接太濃烈 \n我實現不了你想要的每一天每一夜 \n也感覺到了我們之間每一天在改變 \n能不能再給我再一兩天的時間 \n我改變說完了就希望你能諒解 \n我想跟你去你說過的每一間咖啡店 \n讓最初的感覺在這時候繞一個圈\n（空白頁）\n（橋）\n我們的感覺是誤會太擔心對不對 \n你微笑許的願望太直接太濃烈 \n我實現不了你想要的每一天每一夜 \n也感覺到了我們之間每一天在改變\n在離開你之後我包裝了形象 \n周圍朋友都看不出我的情況 \n待人處事慢慢變得謙恭儉讓 \n可是對你的感情還沒拿去典當\n（副）\n我們的感覺是誤會太擔心對不對 \n你微笑許的願望太直接太濃烈 \n我實現不了你想要的每一天每一夜 \n也感覺到了我們之間每一天在改變 \n能不能再給我再一兩天的時間 \n我改變說完了就希望你能諒解 \n我想跟你去你說過的每一間咖啡店 \n讓最初的感覺在這時候繞一個圈",
      "performers": {
        "KB1": "廖丞宥",
        "鼓": "胡彥博",
        "Bass": "黃威翔",
        "主唱1": "陳立品",
        "主唱2": "楊博安",
        "電吉他1": "王婕語",
        "電吉他2": "陳立品"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:10:44.907109+00:00",
      "created_at": "2026-05-08T12:46:28.524+00:00",
      "updated_at": "2026-06-14T16:10:44.907109+00:00",
      "all_members": ""
    },
    {
      "id": "13d804e5-a50d-419a-b5d8-cab1e0605173",
      "title": "The Road Not Taken",
      "arranger": "全體成員",
      "composer": "謝子亮",
      "lyricist": "顏加佳",
      "lyrics": "September skys, there I stood\nRigid minds in yellow woods\nTime has passed and I'm still here\nAt the cross where roads diverge\n\nOne so neat with trails that lead\nOne I once saw in my dreams\n\"You live once,\" so I'm still here \nAt the cross where roads diverge\n\nThe road I once saw in my dreams\nI can't see beyond the horizon\nI don't know what waits for me\nBut I know, I know\n\nI will never come back again\nRight now, right here, then and there \nI will never come back again\nTo take the road not taken\n\n\nWhat if I chose something different \nWould it make all the differences\nWould I tell it with excitement \nOr tell my regrets with a sigh\n\nThe road I once saw in my dreams\nI can't see beyond the horizon\nI don't know what waits for me\nBut I know, I know\n\nI will never come back again\nRight now, right here, then and there \nI will never come back again\nTo take the road not taken\n\nA fall, a cloud, a yellow leaf \nA call of destiny \nA cross, a thought, a gentle breeze \nWhere will you bring me\n\nI will never come back again\nRight now, right here, then and there \nI will never come back again\nTo take the road not taken\n\nSay I'll leave it for another day\nKnowing that way leads on to way\nThen a mystery it will remain \nWhat is down the road not taken",
      "performers": {
        "KB1": "周晴喜",
        "鼓": "邱泳淳",
        "Bass": "黃浩哲",
        "主唱1": "顏加佳",
        "木吉他1": "謝子亮",
        "電吉他1": "王婕語"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:10:42.231241+00:00",
      "created_at": "2026-05-08T12:43:31.664+00:00",
      "updated_at": "2026-06-14T16:10:42.231241+00:00",
      "all_members": ""
    },
    {
      "id": "819dc9fc-4cdb-4194-84d6-9c590436bcee",
      "title": "Lo-fi",
      "arranger": "全體成員",
      "composer": "謝弘楷、林芸禾、周晴喜",
      "lyricist": "謝弘楷",
      "lyrics": "《主歌》\nLo-fi的旋律\n解決大大問題\nIt's a litter crazy\n擾亂你的目的\n\n是你\n用行動來去證明\n揭穿 我的秘密\n\n《導歌》\n就像被夢境肆虐\n在你離開之前\nTracing the lights .lost in the sight\nAnd please call me ,you won't be depressed \n\n《副歌》\nDon't let me be lonely\n享受這份距離\n不再去猶豫\n被渴望的心\n\nYou won't be worried \n故事自有他的邏輯\n再多去想也沒意義\n\n《主歌》\nLo-fi的旋律\n解決大大問題\nIt's a litter crazy\n擾亂你的目的\n\n是你\n用行動來去證明\n揭穿 我的秘密\n\n《導歌》\n就像被夢境肆虐\n在你離開之前\nTracing the lights .lost in the sight\nAnd please call me ,you won't be depressed \n\n《副歌》\nDon't let me be lonely\n享受這份距離\n不再去猶豫\n被渴望的心\n\nYou won't be worried \n故事自有他的邏輯\n再多去想也沒意義\n\n《副歌》\nDon't let me be lonely\n享受這份距離\n不再去猶豫\n被渴望的心\n\nYou won't be worried \n故事自有他的邏輯\n再多去想也沒意義",
      "performers": {
        "KB1": "林韶毅",
        "鼓": "周晴喜",
        "Bass": "黃歆婷",
        "主唱1": "謝弘楷",
        "木吉他1": "林芸禾",
        "電吉他1": "王婕語"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:10:39.914152+00:00",
      "created_at": "2026-05-08T12:39:37.229+00:00",
      "updated_at": "2026-06-14T16:10:39.914152+00:00",
      "all_members": ""
    },
    {
      "id": "8cfffa37-6145-404c-99c8-664d8427bf44",
      "title": "牆",
      "arranger": "全體成員",
      "composer": "謝子亮",
      "lyricist": "謝弘楷",
      "lyrics": "《主歌》\n無人推擠的小巷\n真理藏著一絲痕跡\n虛偽隱藏了過去\n也沒人會去注意\n\n船隻承載著一絲波瀾\n無目的的偏航\n到下一個街口\n是否還有天亮\n\n《副歌》\n推倒他\n逃離陰影之下\n看秩序崩塌\n撫平過往的傷疤\n\n瓦解他\n粉碎一堆殘渣\n被制止的喧嘩\n只剩寂寞在說話\n\n《主歌》\n無人推擠的小巷\n真理藏著一絲痕跡\n虛偽隱藏了過去\n也沒人會去注意\n\n船隻承載著一絲波瀾\n無目的的偏航\n到下一個街口\n是否還有天亮\n\n《副歌》\n推倒他\n逃離陰影之下\n看秩序崩塌\n撫平過往的傷疤\n\n瓦解他\n粉碎一堆殘渣\n被制止的喧嘩\n只剩寂寞在說話\n\n《副歌》\n推倒他\n逃離陰影之下\n看秩序崩塌\n撫平過往的傷疤\n\n瓦解他\n粉碎一堆殘渣\n被制止的喧嘩\n只剩寂寞在說話",
      "performers": {
        "KB1": "廖丞宥",
        "鼓": "胡彥博",
        "Bass": "黃威翔",
        "主唱1": "謝弘楷",
        "主唱2": "謝子亮",
        "電吉他1": "王婕語",
        "電吉他2": "謝子亮"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:10:39.331974+00:00",
      "created_at": "2026-05-08T12:37:47.158+00:00",
      "updated_at": "2026-06-14T16:10:39.331974+00:00",
      "all_members": ""
    },
    {
      "id": "1705bd3f-8b4b-45e0-86d6-0b65ead01bd8",
      "title": "駐足",
      "arranger": "全體成員",
      "composer": "謝子亮",
      "lyricist": "謝弘楷",
      "lyrics": "《主歌》\n鬧鐘還沒把早晨搖醒\n街道在原地流浪\n書頁把昨天翻成過往\n沒說完的話被時間收藏\n\n操場的風 還記得誰在逞強\n笑聲太輕 被歲月放得很響\n把未來說得理所當然\n卻沒人準備 好去承擔\n\n《導歌》\n如果可以晚點被世界發現\n晚點學會什麼叫再見\n把鐘拆開 讓秒針失去路線\n是不是就能停在某個夏天\n\n《副歌》\n我想把時間偷偷折返\n停在不懂的那個夜晚\n如果長大只是換種孤單\n那我寧願再不回來\n把時光鎖在呢喃\n\n讓記憶無限循環\n像沒說出的那句晚安\n世界終究要我們習慣\n可不可以讓我回到從前\n回溯那份時光\n\n《主歌》\n操場的風 還記得誰在逞強\n笑聲太輕 被歲月放得很響\n把未來說得理所當然\n卻沒人準備 好去承擔\n\n《導歌》\n如果可以晚點被世界發現\n晚點學會什麼叫再見\n把鐘拆開 讓秒針失去路線\n是不是就能停在某個夏天\n\n《副歌》\n我想把時間偷偷折返\n停在不懂的那個夜晚\n如果長大只是換種孤單\n那我寧願再不回來\n把時光鎖在呢喃\n\n讓記憶無限循環\n像沒說出的那句晚安\n世界終究要我們習慣\n可不可以讓我回到從前\n回溯那份時光\n\n《橋》\n我是否還停在那個年華\n不想往前的剎那\n在某個無聊的閒暇\n我還會想你嗎\n\n《副歌》\n我想把時間偷偷折返\n停在不懂的那個夜晚\n如果長大只是換種孤單\n那我寧願再不回來\n把時光鎖在呢喃\n\n讓記憶無限循環\n像沒說出的那句晚安\n世界終究要我們習慣\n可不可以讓我回到從前\n回溯那份時光",
      "performers": {
        "KB1": "蔡允弘",
        "鼓": "林育伶",
        "Bass": "黃威翔",
        "主唱1": "謝弘楷",
        "木吉他1": "林芸禾",
        "電吉他1": "謝子亮"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:10:37.016573+00:00",
      "created_at": "2026-05-08T12:26:16.226+00:00",
      "updated_at": "2026-06-14T16:10:37.016573+00:00",
      "all_members": ""
    },
    {
      "id": "65564c93-caa7-4878-b152-91238653aeec",
      "title": "星空",
      "arranger": "全體成員",
      "composer": "許庭睿",
      "lyricist": "謝弘楷",
      "lyrics": "《主歌》\n或許那時的我們都沒睡\n或許那夜的城市也沒醉\n回憶的舊鐵盒 輾轉反側\n想翻閱著什麼 卻又退縮了\n\n或許那些願望還沒兌現\n或許那天的星空 都沒有變\n泛黃的卡片 放在抽屜邊\n像在等個誰 把故事續寫\n\n《導歌》\n好想在人群中看你一眼\n在錯開的時間見你一面\n把遺憾留在那個從前\n\n《副歌》\n好想要再次跟你一起去看流星雨\n還想要完成我們曾經說好的約定\n是不是我太情有獨鍾 或你不肯放手\n不敢去奢求 卻情不自禁伸出手\n\n好想要在那片星空之下遇見你\n還想要找回屬於我們之間的意義\n是你的秘密 我不願追尋\n就別再提起\n\n《主歌》\n或許那些願望還沒兌現\n或許那天的星空 都沒有變\n泛黃的卡片 放在抽屜邊\n像在等個誰 把故事續寫\n\n《導歌》\n好想在人群中看你一眼\n在錯開的時間見你一面\n把遺憾留在那個從前\n\n《副歌》\n好想要再次跟你一起去看流星雨\n還想要完成我們曾經說好的約定\n是不是我太情有獨鍾 或你不肯放手\n不敢去奢求 卻情不自禁伸出手\n\n好想要在那片星空之下遇見你\n還想要找回屬於我們之間的意義\n是你的秘密 我不願追尋\n就別再提起\n\n《副歌》\n好想要再次跟你一起去看流星雨\n還想要完成我們曾經說好的約定\n是不是我太情有獨鍾 或你不肯放手\n不敢去奢求 卻情不自禁伸出手\n\n好想要在那片星空之下遇見你\n還想要找回屬於我們之間的意義\n是你的秘密 我不願追尋\n就別再提起",
      "performers": {
        "鼓": "白鈞任",
        "Bass": "林恩宇",
        "主唱1": "謝弘楷",
        "主唱2": "周晴喜",
        "電吉他1": "許庭睿",
        "電吉他2": "王婕語"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:10:35.379555+00:00",
      "created_at": "2026-05-08T12:22:49.538+00:00",
      "updated_at": "2026-06-14T16:10:35.379555+00:00",
      "all_members": ""
    },
    {
      "id": "ccd8a333-133a-4536-b256-a459cac12552",
      "title": "不留遺憾地留下遺憾",
      "arranger": "白鈞任、李詣超、黃威翔",
      "composer": "陳勁諺、周晴喜",
      "lyricist": "周晴喜",
      "lyrics": "| 主 |\n三番兩次想到你\n不停出現在我夢裡\n眼神總是藏不住\n一對上你眼又臉紅\n\n三番兩次陪著你\n總看你目光追著她\n明明痛得不像話\n也只能笑著說很搭\n\n自作自受\n\n| 副 |\n明明說好不賭不碰\n還不是賭他喜歡我\n哪怕一天都沒停留\n搞了我\n還只會把不確定當藉口\n\n明明說好別再執著\n還不是一次次回頭\n其實也不算他的錯\n只能怪我把衝動當承諾\n\n| 間奏 |\n\n| 主 |\n三番兩次想壓抑\n那鏡頭卻又偏向你\n人群慢慢變背景\n最後都只剩下你\n\n自作自受\n\n| 副 |\n明明說好不賭不碰\n還不是賭他喜歡我\n哪怕一天都沒停留\n搞了我\n還只會把不確定當藉口\n\n明明說好別再執著\n還不是一次次回頭\n其實也不算他的錯\n只能怪我把衝動當承諾\n\n| 間奏 |\n\n| 副 |\n明明說好只當朋友\n那晚你卻拉我的手\n拜託別把衝動當藉口\n連自己都照顧不好就別來搞\n\n最後一次想對你說\n這一年半算我看錯\n感謝你讓我徹底醒過\n只能怪我沒早點放開手",
      "performers": {
        "鼓": "白鈞任",
        "Bass": "黃威翔",
        "主唱1": "陳勁諺",
        "主唱2": "周晴喜",
        "電吉他1": "李詣超"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:10:33.600929+00:00",
      "created_at": "2026-05-01T11:02:27.959+00:00",
      "updated_at": "2026-06-14T16:10:33.600929+00:00",
      "all_members": ""
    },
    {
      "id": "fab6841e-cc69-4b20-a6e7-668d73d0bc24",
      "title": "夫見 貝刂",
      "arranger": "全體成員",
      "composer": "周晴喜、陳勁諺",
      "lyricist": "陳勁諺",
      "lyrics": "| 主 |\n過往不斷閃過\n彷彿人生已經走到盡頭\n浪蕩在繁華街頭\n享受自由的犯囚\n壓抑內心深處\n文明的野獸\n如果都照劇本走\n那又算什麼\n\n| 副 |\n想逃脫現實的賣弄\n沒想到助長了不公\n想打破規則的枷鎖\n轉身跳進自由無底洞\n\n| 間奏 |\n\n| 主 |\n過往不斷閃過\n彷彿人生已經走到盡頭\n浪蕩在繁華街頭\n享受自由的犯囚\n壓抑著內心深處\n文明的野獸\n如果都照劇本走\n那又算什麼\n\n| 副 |\n想逃脫現實的賣弄\n沒想到助長了不公\n想打破規則的枷鎖\n轉身跳進自由無底洞\n裝瀟灑離開不回頭\n波濤洶湧在心中\n連蒙娜麗莎都發愁\n我的人生只由我來說\n\n| 間奏 |\n\n| 橋 |\n你要我回頭\n我就偏往前走\n說嚮往自由生活就快離開被窩\n\n你要我低頭\n我就望向天空\n看那鏡子的小丑\n以為有人在看我以為有人在想我\n\n| 副 |\n想逃脫現實的賣弄\n沒想到助長了不公\n想打破規則的枷鎖\n轉身跳進自由無底洞\n裝瀟灑離開不回頭\n波濤洶湧在心中\n連蒙娜麗莎都發愁\n我的人生只由我來說",
      "performers": {
        "鼓": "白鈞任",
        "Bass": "黃威翔",
        "主唱1": "周晴喜",
        "主唱2": "陳勁諺",
        "電吉他1": "王婕語",
        "電吉他2": "陳立品"
      },
      "is_eliminated": true,
      "eliminated_at": "2026-06-14T16:10:05.125717+00:00",
      "created_at": "2026-04-30T07:07:32.359+00:00",
      "updated_at": "2026-06-14T16:10:05.125717+00:00",
      "all_members": ""
    }
  ],
  "cullNotes": [

  ]
};
